org: luisawork
service: live020

package:
  individually: true

provider:
  name: aws
  region: us-east-1
  runtime: nodejs20.x
  deploymentMethod: direct
  architecture: arm64

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    target: node20
    exclude:
      - '@aws-sdk/*'
    define:
      require.resolve: undefined
    platform: node
    concurrency: 10

resources:
  Resources:
    LiveUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: live020-UserPool
        MfaConfiguration: OFF
        AutoVerifiedAttributes:
          - email
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: false
        UsernameAttributes:
          - email
        AccountRecoverySetting:
          RecoveryMechanisms:
            - Name: verified_email
              Priority: 1
        Policies:
          PasswordPolicy:
            MinimumLength: 10
            RequireUppercase: false
            RequireLowercase: false
            RequireNumbers: false
            RequireSymbols: false
            TemporaryPasswordValidityDays: 2
        Schema:
          - Name: given_name
            Required: true
            Mutable: true
            AttributeDataType: String
          - Name: family_name
            Required: false
            Mutable: true
            AttributeDataType: String
    LiveUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: live020-UserPool-Client
        UserPoolId: !Ref LiveUserPool
        ExplicitAuthFlows:
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        TokenValidityUnits:
          AccessToken: hours
          RefreshToken: days
        AccessTokenValidity: 3
        RefreshTokenValidity: 48

functions:
  hello:
    handler: src/functions/hello.handler
    events:
      - httpApi:
          method: GET
          path: /hello
